// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiApp.DataAccess;

namespace TaxiApp.Migrations
{
    [DbContext(typeof(TaxiContext))]
    partial class TaxiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaxiApp.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5728e22d-764f-4c2d-8261-88dd9dea3b19"),
                            Latitude = 20.5,
                            Longitude = 70.400000000000006,
                            NumberPhone = "+4654651487"
                        },
                        new
                        {
                            Id = new Guid("e0834afb-bb26-4351-adcb-22d7bca64fb6"),
                            Latitude = 74.799999999999997,
                            Longitude = 73.099999999999994,
                            NumberPhone = "+9856489724"
                        },
                        new
                        {
                            Id = new Guid("dac33980-9e9f-4b9b-8d06-e7116d454687"),
                            Latitude = 12.699999999999999,
                            Longitude = 60.200000000000003,
                            NumberPhone = "+4684654878"
                        },
                        new
                        {
                            Id = new Guid("892de076-036e-4a90-8c7f-380bade72b07"),
                            Latitude = 68.120000000000005,
                            Longitude = 52.409999999999997,
                            NumberPhone = "+6874545582"
                        });
                });

            modelBuilder.Entity("TaxiApp.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumberCar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("558cdddb-9b5d-4328-89b4-86e0b05763c1"),
                            NumberCar = "875AKW"
                        },
                        new
                        {
                            Id = new Guid("e4a30b61-5cd6-4f73-bb18-dd16461c4dd7"),
                            NumberCar = "824ODQ"
                        },
                        new
                        {
                            Id = new Guid("0b28c25e-fcfc-40e7-a30d-6c16ffaa131c"),
                            NumberCar = "184UEN"
                        },
                        new
                        {
                            Id = new Guid("c4357dc2-1175-4eac-a945-4ce5ad724c3f"),
                            NumberCar = "461LEN"
                        });
                });

            modelBuilder.Entity("TaxiApp.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumberCar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72494704-82c3-44bf-bae4-b5e8cf185474"),
                            NumberCar = "824ODQ",
                            PhoneClient = "+9856489724",
                            State = "Waiting"
                        },
                        new
                        {
                            Id = new Guid("77226738-eee7-4403-bb25-c9d451348449"),
                            NumberCar = "461LEN",
                            PhoneClient = "+4654651487",
                            State = "InProcess"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
